import Link from "next/link";
import { notFound } from "next/navigation";
import { ActionForm } from "@/components/action-form";
import { getTenantPageContext } from "@/lib/page-context";
import { recordLoanPayment, rescheduleLoanInstallment, setEmployeeLoanStatus } from "../../actions";

export const dynamic = "force-dynamic";

function money(value: number | string | null | undefined, currency: string, locale: string) {
  return new Intl.NumberFormat(locale === "ar" ? "ar-EG" : "en-EG", { style: "currency", currency, maximumFractionDigits: 2 }).format(Number(value ?? 0));
}

export default async function LoanStatementPage({ params }: { params: Promise<{ locale: string; loanId: string }> }) {
  const { locale: rawLocale, loanId } = await params;
  const { locale, dictionary: d, supabase, membership } = await getTenantPageContext(rawLocale);
  if (!membership) return <div className="card">{d.noCompany}</div>;
  const tenantId = membership.tenant_id;
  const today = new Date().toISOString().slice(0, 10);
  const copy = locale === "ar" ? {
    back: "العودة للسلف", statement: "كشف السلفة", approved: "المبلغ المعتمد", paid: "المسدد", remaining: "المتبقي", monthly: "القسط الشهري", progress: "تقدم السداد", schedule: "جدول الأقساط", number: "القسط", due: "تاريخ الاستحقاق", original: "التاريخ الأصلي", amount: "المبلغ", status: "الحالة", noSchedule: "لا يوجد جدول أقساط.", payments: "حركة السداد", date: "التاريخ", method: "الطريقة", reference: "المرجع", noPayments: "لم تسجل دفعات بعد.", record: "تسجيل دفعة", recordHelp: "توزع الدفعة تلقائياً على أقدم الأقساط غير المسددة.", notes: "ملاحظات", savePayment: "حفظ الدفعة", paymentSaved: "تم تسجيل الدفعة وتحديث الرصيد.", reschedule: "تأجيل", rescheduleReason: "سبب التأجيل", newDate: "التاريخ الجديد", rescheduled: "تم تحديث تاريخ القسط.", pause: "إيقاف مؤقت", resume: "استئناف", writeOff: "شطب الرصيد", statusNote: "سبب تغيير الحالة", statusSaved: "تم تحديث حالة السلفة.", settle: "تسوية مبكرة", employee: "الموظف", saving: d.saving, failed: d.actionFailed,
  } : {
    back: "Back to loans", statement: "Loan statement", approved: "Approved", paid: "Paid", remaining: "Remaining", monthly: "Monthly installment", progress: "Repayment progress", schedule: "Installment schedule", number: "Installment", due: "Due date", original: "Original date", amount: "Amount", status: "Status", noSchedule: "No installment schedule.", payments: "Payment ledger", date: "Date", method: "Method", reference: "Reference", noPayments: "No payments recorded yet.", record: "Record payment", recordHelp: "Payments automatically allocate to the oldest open installments.", notes: "Notes", savePayment: "Save payment", paymentSaved: "Payment recorded and balance updated.", reschedule: "Reschedule", rescheduleReason: "Reschedule reason", newDate: "New due date", rescheduled: "Installment due date updated.", pause: "Pause", resume: "Resume", writeOff: "Write off balance", statusNote: "Status-change reason", statusSaved: "Loan status updated.", settle: "Early settlement", employee: "Employee", saving: d.saving, failed: d.actionFailed,
  };

  const [{ data: loan, error: loanError }, { data: installments, error: installmentError }, { data: payments, error: paymentError }, { data: canManage }] = await Promise.all([
    supabase.from("employee_loans").select("id,employee_id,loan_number,approved_amount,installment_count,monthly_installment,start_month,currency_code,total_paid,remaining_balance,status,notes,approved_at").eq("tenant_id", tenantId).eq("id", loanId).maybeSingle(),
    supabase.from("loan_installments").select("id,installment_number,due_date,original_due_date,amount,paid_amount,status,defer_reason,paid_at").eq("tenant_id", tenantId).eq("loan_id", loanId).order("installment_number"),
    supabase.from("loan_payments").select("id,installment_id,amount,payment_date,method,reference,notes,created_at").eq("tenant_id", tenantId).eq("loan_id", loanId).order("payment_date", { ascending: false }),
    supabase.rpc("has_permission", { p_tenant_id: tenantId, p_permission: "loans.manage" }),
  ]);
  if (loanError) throw loanError; if (installmentError) throw installmentError; if (paymentError) throw paymentError; if (!loan) notFound();
  const { data: employee } = await supabase.from("employees").select("id,employee_code,name_en,name_ar,position").eq("id", loan.employee_id).maybeSingle();
  const progress = Number(loan.approved_amount) ? Math.min(100, Number(loan.total_paid) / Number(loan.approved_amount) * 100) : 0;

  return <>
    <div className="page-head loan-statement-head"><div><Link className="back-link" href={`/${locale}/loans`}>← {copy.back}</Link><h1 className="page-title">{loan.loan_number}</h1><p className="muted">{copy.statement} · {loan.start_month}</p></div><span className={`badge loan-status-${loan.status}`}>{loan.status}</span></div>
    <section className="card loan-identity"><div className="payroll-person"><span>{(employee?.name_en ?? "E").slice(0, 2).toUpperCase()}</span><div><Link href={`/${locale}/employees/${employee?.id}`}><strong>{locale === "ar" && employee?.name_ar ? employee.name_ar : employee?.name_en}</strong></Link><small>{employee?.employee_code} · {employee?.position ?? copy.employee}</small></div></div>{canManage && !["settled", "written_off"].includes(loan.status) ? <div className="loan-status-actions"><ActionForm action={setEmployeeLoanStatus.bind(null, locale, loan.id, loan.status === "paused" ? "active" : "paused")} errorMessage={copy.failed} pendingMessage={copy.saving} successMessage={copy.statusSaved}><button className="button secondary small-button" type="submit">{loan.status === "paused" ? copy.resume : copy.pause}</button></ActionForm><details><summary className="button ghost small-button danger-text">{copy.writeOff}</summary><ActionForm action={setEmployeeLoanStatus.bind(null, locale, loan.id, "written_off")} className="inline-form loan-writeoff-form" confirmMessage={copy.writeOff} errorMessage={copy.failed} pendingMessage={copy.saving} successMessage={copy.statusSaved}><input className="input" name="statusNote" placeholder={copy.statusNote} required /><button className="button danger" type="submit">{copy.writeOff}</button></ActionForm></details></div> : null}</section>
    <section className="stats-grid business-stats section-gap"><div className="stat-card"><span>{copy.approved}</span><strong>{money(loan.approved_amount, loan.currency_code, locale)}</strong><small>{loan.installment_count} {copy.number.toLowerCase()}</small></div><div className="stat-card"><span>{copy.paid}</span><strong>{money(loan.total_paid, loan.currency_code, locale)}</strong><small>{progress.toFixed(0)}%</small></div><div className="stat-card"><span>{copy.remaining}</span><strong>{money(loan.remaining_balance, loan.currency_code, locale)}</strong><small>{loan.currency_code}</small></div><div className="stat-card"><span>{copy.monthly}</span><strong>{money(loan.monthly_installment, loan.currency_code, locale)}</strong><small>{loan.start_month}</small></div></section>
    <section className="card stack section-gap"><div className="section-title-row"><div><h2>{copy.progress}</h2><p className="muted">{money(loan.total_paid, loan.currency_code, locale)} / {money(loan.approved_amount, loan.currency_code, locale)}</p></div><strong>{progress.toFixed(1)}%</strong></div><div className="loan-progress large"><span style={{ width: `${progress}%` }} /></div></section>

    {canManage && !["settled", "written_off"].includes(loan.status) ? <section className="card stack section-gap"><details className="business-create-panel"><summary><span><strong>{copy.record}</strong><small>{copy.recordHelp}</small></span><span className="button small-button">{d.add}</span></summary><ActionForm action={recordLoanPayment.bind(null, locale, loan.id)} className="form-grid business-form" errorMessage={copy.failed} pendingMessage={copy.saving} resetOnSuccess successMessage={copy.paymentSaved}><div className="field"><label>{copy.amount}</label><input className="input" defaultValue={loan.remaining_balance} max={loan.remaining_balance} min="0.01" name="amount" required step="0.01" type="number" /></div><div className="field"><label>{copy.date}</label><input className="input" defaultValue={today} name="paymentDate" required type="date" /></div><div className="field"><label>{copy.method}</label><select className="select" defaultValue="cash" name="method"><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="settlement">{copy.settle}</option><option value="adjustment">Adjustment</option></select></div><div className="field"><label>{copy.reference}</label><input className="input" name="reference" /></div><div className="field full"><label>{copy.notes}</label><textarea className="textarea" name="notes" /></div><button className="button full" type="submit">{copy.savePayment}</button></ActionForm></details></section> : null}

    <section className="card stack section-gap"><div className="section-title-row"><div><h2>{copy.schedule}</h2><p className="muted">{copy.recordHelp}</p></div><span className="badge">{installments?.length ?? 0}</span></div><div className="installment-list">{installments?.map((installment) => <article className={`installment-card installment-${installment.status}`} key={installment.id}><div className="installment-number"><span>{copy.number}</span><strong>{installment.installment_number}</strong></div><div><span>{copy.due}</span><strong>{installment.due_date}</strong>{installment.due_date !== installment.original_due_date ? <small>{copy.original}: {installment.original_due_date}</small> : null}</div><div><span>{copy.amount}</span><strong>{money(installment.amount, loan.currency_code, locale)}</strong><small>{money(installment.paid_amount, loan.currency_code, locale)} {copy.paid.toLowerCase()}</small></div><span className={`badge installment-status-${installment.status}`}>{installment.status}</span>{canManage && !["deducted", "paid", "waived"].includes(installment.status) ? <details className="installment-reschedule"><summary>{copy.reschedule}</summary><ActionForm action={rescheduleLoanInstallment.bind(null, locale, loan.id, installment.id)} className="inline-form" errorMessage={copy.failed} pendingMessage={copy.saving} successMessage={copy.rescheduled}><input className="input" defaultValue={installment.due_date} name="dueDate" title={copy.newDate} type="date" /><input className="input" name="reason" placeholder={copy.rescheduleReason} required /><button className="button secondary" type="submit">{copy.reschedule}</button></ActionForm></details> : null}</article>)}{!installments?.length ? <div className="empty">{copy.noSchedule}</div> : null}</div></section>

    <section className="card stack section-gap"><div className="section-title-row"><div><h2>{copy.payments}</h2><p className="muted">{copy.statement}</p></div><span className="badge">{payments?.length ?? 0}</span></div><div className="table-wrap"><table className="business-table"><thead><tr><th>{copy.date}</th><th>{copy.amount}</th><th>{copy.method}</th><th>{copy.reference}</th><th>{copy.notes}</th></tr></thead><tbody>{payments?.map((payment) => <tr key={payment.id}><td>{payment.payment_date}</td><td><strong>{money(payment.amount, loan.currency_code, locale)}</strong></td><td><span className="badge">{payment.method.replaceAll("_", " ")}</span></td><td>{payment.reference ?? "—"}</td><td>{payment.notes ?? "—"}</td></tr>)}</tbody></table>{!payments?.length ? <div className="empty">{copy.noPayments}</div> : null}</div></section>
  </>;
}
