import Link from "next/link";
import { notFound } from "next/navigation";
import { ActionForm } from "@/components/action-form";
import { getTenantPageContext } from "@/lib/page-context";
import { addTaskComment, cancelOperationalTask, reviewTaskEvidence, startTaskAssignment, submitTaskEvidence } from "../../actions";

export const dynamic = "force-dynamic";

export default async function TaskDetailPage({ params }: { params: Promise<{ locale: string; taskId: string }> }) {
  const { locale: rawLocale, taskId } = await params;
  const { locale, dictionary: d, supabase, user, membership } = await getTenantPageContext(rawLocale);
  if (!membership) return <div className="card">{d.noCompany}</div>;
  const tenantId = membership.tenant_id;
  const copy = locale === "ar" ? {
    back: "العودة إلى المهام", assigned: "المسند إليهم", activity: "التحديثات والتعليقات", starts: "تبدأ", due: "الموعد النهائي", recurring: "التكرار", evidence: "دليل الإنجاز مطلوب", start: "بدء المهمة", started: "تم بدء المهمة.", submit: "إرسال للمراجعة", submitHelp: "أضف ملاحظتك وارفع صوراً أو ملفات PDF كدليل.", notes: "ملاحظات الإنجاز", files: "الصور أو ملفات PDF", submitted: "تم إرسال المهمة للمراجعة.", approve: "اعتماد", changes: "طلب تعديلات", reviewNote: "ملاحظة المراجع", approved: "تم اعتماد الإنجاز.", rejected: "تم طلب التعديلات.", comments: "اكتب تحديثاً أو سؤالاً…", comment: "إضافة تعليق", commented: "تمت إضافة التعليق.", cancel: "إلغاء المهمة", cancelReason: "سبب الإلغاء", cancelled: "تم إلغاء المهمة.", noComments: "لا توجد تحديثات بعد.", submissions: "محاولات التسليم", openFile: "فتح المرفق", failed: "تعذر حفظ التغيير. حاول مرة أخرى.", saving: "جارٍ الحفظ…", people: "موظف", overdue: "متأخرة", completed: "مكتملة",
  } : {
    back: "Back to tasks", assigned: "Assigned people", activity: "Updates & comments", starts: "Starts", due: "Due", recurring: "Recurrence", evidence: "Completion evidence required", start: "Start task", started: "Task started.", submit: "Submit for review", submitHelp: "Add a completion note and upload photos or PDFs as evidence.", notes: "Completion notes", files: "Photos or PDFs", submitted: "Task submitted for review.", approve: "Approve", changes: "Request changes", reviewNote: "Reviewer note", approved: "Work approved.", rejected: "Changes requested.", comments: "Write an update or question…", comment: "Add comment", commented: "Comment added.", cancel: "Cancel task", cancelReason: "Cancellation reason", cancelled: "Task cancelled.", noComments: "No updates yet.", submissions: "Submission history", openFile: "Open attachment", failed: "Could not save the change. Try again.", saving: "Saving…", people: "people", overdue: "Overdue", completed: "Completed",
  };
  const [{ data: task, error: taskError }, { data: assignments, error: assignmentError }, { data: employees, error: employeeError }, { data: submissions, error: submissionError }, { data: attachments, error: attachmentError }, { data: comments, error: commentError }, { data: canManage }, { data: canApprove }] = await Promise.all([
    supabase.from("tasks").select("*").eq("tenant_id", tenantId).eq("id", taskId).maybeSingle(),
    supabase.from("task_assignments").select("*").eq("tenant_id", tenantId).eq("task_id", taskId).order("assigned_at"),
    supabase.from("employees").select("id,user_id,employee_code,name_en,name_ar,position").eq("tenant_id", tenantId),
    supabase.from("task_submissions").select("*").eq("tenant_id", tenantId).order("submitted_at", { ascending: false }),
    supabase.from("task_attachments").select("*").eq("tenant_id", tenantId),
    supabase.from("task_comments").select("*").eq("tenant_id", tenantId).eq("task_id", taskId).order("created_at"),
    supabase.rpc("has_permission", { p_tenant_id: tenantId, p_permission: "tasks.manage" }),
    supabase.rpc("has_permission", { p_tenant_id: tenantId, p_permission: "tasks.approve" }),
  ]);
  for (const error of [taskError, assignmentError, employeeError, submissionError, attachmentError, commentError]) if (error) throw error;
  if (!task) notFound();
  const employeeMap = new Map((employees ?? []).map((employee) => [employee.id, employee]));
  const employeeByUser = new Map((employees ?? []).filter((employee) => employee.user_id).map((employee) => [employee.user_id!, employee]));
  const assignmentRows = assignments ?? []; const submissionRows = (submissions ?? []).filter((submission) => assignmentRows.some((assignment) => assignment.id === submission.assignment_id));
  const attachmentRows = (attachments ?? []).filter((attachment) => submissionRows.some((submission) => submission.id === attachment.submission_id));
  const signedUrls = new Map<string, string>();
  await Promise.all(attachmentRows.map(async (attachment) => { const { data } = await supabase.storage.from("task-evidence").createSignedUrl(attachment.storage_path, 3600); if (data?.signedUrl) signedUrls.set(attachment.id, data.signedUrl); }));
  const currentEmployee = employeeByUser.get(user.id); const mine = assignmentRows.find((assignment) => assignment.employee_id === currentEmployee?.id);
  const overdue = !["approved", "cancelled"].includes(task.status) && new Date(task.due_at).getTime() < new Date().getTime();
  return <>
    <div className="page-head"><div><Link className="text-link" href={`/${locale}/tasks`}>← {copy.back}</Link><h1 className="page-title task-detail-title">{locale === "ar" && task.title_ar ? task.title_ar : task.title_en}</h1><p className="muted">{locale === "ar" && task.description_ar ? task.description_ar : task.description_en}</p></div><div className="page-head-actions"><span className={`badge task-priority-badge-${task.priority}`}>{task.priority}</span><span className={`badge task-status-${overdue ? "overdue" : task.status}`}>{overdue ? copy.overdue : task.status.replaceAll("_", " ")}</span></div></div>
    <section className="card task-detail-summary"><div><span>{copy.starts}</span><strong>{new Date(task.start_at).toLocaleString(locale, { dateStyle: "medium", timeStyle: "short" })}</strong></div><div><span>{copy.due}</span><strong>{new Date(task.due_at).toLocaleString(locale, { dateStyle: "medium", timeStyle: "short" })}</strong></div><div><span>{copy.recurring}</span><strong>{task.recurrence === "none" ? d.no : `${task.recurrence} · #${task.occurrence_number}`}</strong></div><div><span>{copy.assigned}</span><strong>{assignmentRows.length} {copy.people}</strong></div>{task.require_evidence ? <div className="task-evidence-callout">{copy.evidence}</div> : null}</section>
    {mine && ["assigned", "rejected"].includes(mine.status) && task.status !== "cancelled" ? <section className="card section-gap"><ActionForm action={startTaskAssignment.bind(null, locale, task.id, mine.id)} errorMessage={copy.failed} pendingMessage={copy.saving} successMessage={copy.started}><button className="button" type="submit">{copy.start}</button></ActionForm></section> : null}
    {mine && ["assigned", "in_progress", "rejected"].includes(mine.status) && task.status !== "cancelled" ? <section className="card stack section-gap"><h2>{copy.submit}</h2><p className="muted">{copy.submitHelp}</p><ActionForm action={submitTaskEvidence.bind(null, locale, tenantId, task.id, mine.id)} className="form-grid" errorMessage={copy.failed} pendingMessage={copy.saving} successMessage={copy.submitted}><div className="field full"><label>{copy.notes}</label><textarea className="textarea" name="notes" rows={3} /></div><div className="field full"><label>{copy.files}</label><input accept="image/jpeg,image/png,image/webp,application/pdf" className="input file-input" multiple name="evidence" required={task.require_evidence} type="file" /></div><button className="button full" type="submit">{copy.submit}</button></ActionForm></section> : null}
    <section className="card stack section-gap"><div className="section-title-row"><div><h2>{copy.assigned}</h2><p className="muted">{task.title_en}</p></div><span className="badge">{assignmentRows.length}</span></div><div className="task-assignment-list">{assignmentRows.map((assignment) => { const employee = employeeMap.get(assignment.employee_id); const history = submissionRows.filter((submission) => submission.assignment_id === assignment.id); return <article className="task-assignment-card" key={assignment.id}><div className="task-assignment-person"><span className="person-avatar">{employee?.name_en.slice(0, 1) ?? "?"}</span><span><strong>{employee ? (locale === "ar" && employee.name_ar ? employee.name_ar : employee.name_en) : d.employeeAccount}</strong><small>{employee?.position ?? employee?.employee_code}</small></span><span className={`badge task-status-${assignment.status}`}>{assignment.status.replaceAll("_", " ")}</span></div>{assignment.review_note ? <p className="business-note">{assignment.review_note}</p> : null}{history.length ? <details className="submission-history"><summary>{history.length} {copy.submissions}</summary>{history.map((submission) => <div className="submission-entry" key={submission.id}><div><strong>#{submission.submission_number}</strong><time>{new Date(submission.submitted_at).toLocaleString(locale, { dateStyle: "medium", timeStyle: "short" })}</time>{submission.decision ? <span className={`badge task-status-${submission.decision}`}>{submission.decision}</span> : null}</div>{submission.notes ? <p>{submission.notes}</p> : null}<div className="attachment-list">{attachmentRows.filter((attachment) => attachment.submission_id === submission.id).map((attachment) => signedUrls.get(attachment.id) ? <a className="attachment-link" href={signedUrls.get(attachment.id)} key={attachment.id} rel="noreferrer" target="_blank">{attachment.file_name} · {copy.openFile}</a> : null)}</div></div>)}</details> : null}{assignment.status === "submitted" && (canApprove || canManage) ? <div className="task-review-actions"><ActionForm action={reviewTaskEvidence.bind(null, locale, task.id, assignment.id, true)} errorMessage={copy.failed} pendingMessage={copy.saving} successMessage={copy.approved}><button className="button small-button" type="submit">{copy.approve}</button></ActionForm><ActionForm action={reviewTaskEvidence.bind(null, locale, task.id, assignment.id, false)} className="inline-form" errorMessage={copy.failed} pendingMessage={copy.saving} successMessage={copy.rejected}><input className="input" name="reviewNote" placeholder={copy.reviewNote} required /><button className="button danger small-button" type="submit">{copy.changes}</button></ActionForm></div> : null}</article>; })}</div></section>
    <section className="card stack section-gap"><h2>{copy.activity}</h2><div className="task-comment-list">{(comments ?? []).map((comment) => { const author = comment.author_user_id ? employeeByUser.get(comment.author_user_id) : null; return <article key={comment.id}><span className="person-avatar mini-avatar">{author?.name_en.slice(0, 1) ?? "S"}</span><div><strong>{author ? (locale === "ar" && author.name_ar ? author.name_ar : author.name_en) : d.companyUser}</strong><time>{new Date(comment.created_at).toLocaleString(locale, { dateStyle: "medium", timeStyle: "short" })}</time><p>{comment.body}</p></div></article>; })}{!comments?.length ? <div className="empty">{copy.noComments}</div> : null}</div>{task.status !== "cancelled" ? <ActionForm action={addTaskComment.bind(null, locale, task.id)} className="inline-form task-comment-form" errorMessage={copy.failed} pendingMessage={copy.saving} resetOnSuccess successMessage={copy.commented}><input className="input" name="body" placeholder={copy.comments} required /><button className="button" type="submit">{copy.comment}</button></ActionForm> : null}</section>
    {canManage && !["approved", "cancelled"].includes(task.status) ? <section className="card danger-zone section-gap"><h2>{copy.cancel}</h2><ActionForm action={cancelOperationalTask.bind(null, locale, task.id)} className="inline-form" confirmMessage={copy.cancel} errorMessage={copy.failed} pendingMessage={copy.saving} successMessage={copy.cancelled}><input className="input" name="reason" placeholder={copy.cancelReason} required /><button className="button danger" type="submit">{copy.cancel}</button></ActionForm></section> : null}
  </>;
}
